name: arcist
description: "Arcist is part of the Arc ecosystem."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  http: ^1.2.0
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  msix: ^3.18.0

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Icon.png"
  # This tells Android exactly what color to use for its forced background shape
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/Icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/Icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/
