name: arcist
description: "Arcist is part of the Arc ecosystem."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.8
  http: ^1.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Native Splash Screen Configuration to block the default blue logo
flutter_native_splash:
  color: "#000000"
  fullscreen: true

  # Android 12+ specific override to match background and block default icons
  android_12:
    color: "#000000"
    icon_background_color: "#000000"